import Link from "next/link";
import type { Metadata } from "next";
import { CtaBand, SiteShell } from "./_components/SiteShell";
import { departments, faqs, prices, services } from "./_data/content";

const steps = [
  ["01", "▤", "Décrivez votre projet", "Ville, type de déchet et volume : trois informations suffisent."],
  ["02", "✉", "Recevez votre devis", "Notre équipe vous répond par e-mail avec une proposition adaptée à votre chantier."],
  ["03", "✓", "Validez votre réservation", "Les conditions et la disponibilité sont confirmées avec vous avant toute réservation."],
  ["04", "▰", "On s’occupe du reste", "Livraison, enlèvement et traitement sont gérés par notre partenaire local."],
];

export const metadata: Metadata = { alternates: { canonical: "/" } };

export default function Home() {
  const faqSchema = { "@context":"https://schema.org", "@type":"FAQPage", mainEntity: faqs.map(([name,text]) => ({ "@type":"Question", name, acceptedAnswer:{ "@type":"Answer", text } })) };
  const orgSchema = { "@context":"https://schema.org", "@type":"Organization", name:"MaBenneEnLigne", url:"https://www.mabenneenligne.fr", email:"contact@mabenneenligne.fr" };
  return <SiteShell>
    <section className="home-hero"><div className="hero-backdrop" /><div className="container hero-content"><span className="hero-badge"><b>🚛</b> N°1 de la location de benne en ligne <i /> Toute la France</span><h1>Louez votre benne<br />en <span>2 minutes.</span></h1><h2>Livrée en 24h.</h2><p>Comparez, réservez et faites-vous livrer une benne pour vos gravats, encombrants ou déchets verts. Service disponible dans <strong>45+ départements.</strong></p><div className="hero-actions"><Link className="button button-large" href="/devis">Demander mon devis gratuit <span>→</span></Link><Link className="button button-ghost button-large" href="/comment-ca-marche">Comment ça marche ?</Link></div><div className="hero-trust"><span>✓ Devis gratuit</span><span>✓ Sans engagement</span><span>✓ Réponse sous 30 min</span></div></div><div className="hero-availability"><strong><span>●</span> Disponible dans votre département</strong><small>Livraison possible dès demain*</small></div></section>
    <section className="stats-strip"><div className="container"><div><strong>850<span>+</span></strong><small>Bennes posées en 2026</small></div><div><strong>45<span>+</span></strong><small>Départements couverts</small></div><div><strong>98<span>%</span></strong><small>Clients satisfaits</small></div><div><strong>24<span>h</span></strong><small>Délai moyen de livraison</small></div></div></section>
    <section className="section how"><div className="container"><div className="section-heading centered"><span className="eyebrow">Simple comme bonjour</span><h2>Votre benne en <em>4 étapes</em></h2><p>Un parcours pensé pour vous faire gagner du temps, sans appel interminable ni mauvaise surprise.</p></div><div className="step-grid">{steps.map(([n,icon,title,text],i) => <div className="step-card" key={n}><span className="step-number">{n}</span><div className="step-icon">{icon}</div><h3>{title}</h3><p>{text}</p>{i < 3 && <b className="step-arrow">→</b>}</div>)}</div><div className="center"><Link className="text-link" href="/comment-ca-marche">Découvrir le fonctionnement en détail <span>→</span></Link></div></div></section>
    <section className="section services-section"><div className="container"><div className="section-heading split"><div><span className="eyebrow">À chaque projet sa benne</span><h2>Que souhaitez-vous <em>évacuer ?</em></h2></div><p>Nos partenaires prennent en charge tous les déchets courants de chantier, dans le respect des filières agréées.</p></div><div className="service-grid">{Object.entries(services).map(([slug,s]) => <Link className="service-card" href={`/nos-services/${slug}`} key={slug}><div className="service-image" style={{ backgroundImage: `url(${s.image})` }}><span>Disponible</span></div><div><h3>{s.short}</h3><p>{s.waste}</p><b>Voir les bennes <span>→</span></b></div></Link>)}</div></div></section>
    <section className="section pricing-home"><div className="container"><div className="section-heading centered"><span className="eyebrow">Des prix clairs</span><h2>Combien coûte votre <em>benne ?</em></h2><p>Livraison, 7 jours de location, enlèvement et traitement inclus.</p></div><div className="table-wrap"><table><thead><tr><th>Volume</th><th>Gravats</th><th>DIB / Tout-venant</th><th>Déchets verts</th></tr></thead><tbody>{prices.slice(0,4).map(p => <tr key={p.volume}><th>{p.volume}</th><td><small>À partir de</small><strong>{p.gravats}</strong></td><td><small>À partir de</small><strong>{p.dib}</strong></td><td><small>À partir de</small><strong>{p.verts}</strong></td></tr>)}</tbody></table></div><div className="pricing-note"><span>✓ Prix tout compris</span><span>✓ Aucun frais caché</span><Link className="button" href="/devis">Obtenir mon prix exact <span>→</span></Link></div></div></section>
    <section className="section why"><div className="container"><div className="section-heading centered light"><span className="eyebrow light">L’assurance d’un service bien fait</span><h2>Pourquoi choisir <em>MaBenneEnLigne ?</em></h2></div><div className="why-grid"><article><span>⌖</span><h3>Réseau local sélectionné</h3><p>Nous cherchons le partenaire adapté à votre zone et au type de déchets à évacuer.</p><small>Solution adaptée au chantier</small></article><article><span>ϟ</span><h3>Échanges par e-mail</h3><p>Votre demande est traitée par écrit, avec les informations utiles pour comparer et décider.</p><small>Réponse 6j/7</small></article><article><span>◇</span><h3>Devis détaillé</h3><p>Les conditions de livraison, location, enlèvement et traitement sont précisées avant validation.</p><small>Pas de réservation automatique</small></article></div></div></section>
    <section className="section testimonials"><div className="container"><div className="section-heading split"><div><span className="eyebrow">Ils nous font confiance</span><h2>Des chantiers qui avancent, <em>des clients sereins.</em></h2></div><div className="rating"><strong>4,9</strong><span>★★★★★<small>Basé sur nos avis clients</small></span></div></div><div className="testimonial-grid">{[["Benne livrée le lendemain matin, chauffeur très professionnel. Je recommande !","Jean-Marc P.","Lille (59)"],["Service client au top, le prix annoncé était le prix final. Rien à redire.","Sophie L.","Orléans (45)"],["J’ai comparé avec trois loueurs locaux : meilleur prix et meilleur suivi.","Marc D.","Lyon (69)"]].map(([q,n,c]) => <blockquote key={n}><div>★★★★★</div><p>“{q}”</p><footer><span>{n[0]}</span><strong>{n}<small>{c}</small></strong><i>✓ Vérifié</i></footer></blockquote>)}</div><p className="disclosure">Témoignages de lancement illustratifs, à remplacer progressivement par des avis clients vérifiés.</p></div></section>
    <section className="section coverage"><div className="container coverage-grid"><div><span className="eyebrow">Un réseau qui grandit chaque jour</span><h2>Nous livrons partout <em>en France.</em></h2><p>Notre réseau de transporteurs locaux couvre déjà plus de 45 départements. Vérifiez la disponibilité près de chez vous.</p><div className="dept-mini-grid">{departments.map(d => <Link href={`/departements/${d.slug}`} key={d.code}><b>{d.code}</b><span>{d.name}<small><i /> Disponible</small></span></Link>)}</div><Link className="button" href="/departements">Voir tous les départements <span>→</span></Link></div><div className="network-visual"><span className="network-ring ring-one" /><span className="network-ring ring-two" /><div className="france-shape">FR<span>45+<small>départements</small></span></div><b className="dot d1" /><b className="dot d2" /><b className="dot d3" /><b className="dot d4" /><b className="dot d5" /></div></div></section>
    <section className="partner-band"><div className="container"><div className="partner-icon">▰</div><div><span>Vous êtes loueur de bennes ?</span><h2>Rejoignez notre réseau national.</h2><p>Des commandes payées avant livraison. Zéro prospection, zéro impayé.</p></div><Link className="button button-light" href="/devenir-partenaire">Devenir partenaire <span>→</span></Link></div></section>
    <section className="section faq-home"><div className="container faq-layout"><div><span className="eyebrow">On répond à vos questions</span><h2>Tout savoir avant de <em>réserver.</em></h2><p>Une question spécifique ? Écrivez-nous ou faites votre demande de devis.</p><Link className="button button-secondary" href="/contact">Nous écrire</Link></div><div className="accordion">{faqs.map(([q,a],i) => <details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}<Link className="text-link" href="/faq">Voir toutes les questions <span>→</span></Link></div></div></section>
    <CtaBand title="Votre chantier mérite d’avancer." text="Obtenez votre devis gratuit en deux minutes. Notre équipe vous répond par e-mail." />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(orgSchema) }} />
  </SiteShell>;
}
